# Generated by Django 5.0.1 on 2024-01-22 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("threadio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replies",
                to="threadio.thread",
            ),
        ),
    ]
