# Generated by Django 5.0.1 on 2024-01-22 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediaroomio", "0001_initial"),
        ("threadio", "0002_thread_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="file",
        ),
        migrations.AddField(
            model_name="thread",
            name="media_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="mediaroomio.mediaroom",
            ),
        ),
    ]
