# Generated by Django 5.0.1 on 2024-01-22 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("threadio", "0003_remove_thread_file_thread_media_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threadread",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="threadio.chatgroup",
            ),
        ),
    ]
