# Generated by Django 5.0.1 on 2024-01-23 07:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("threadio", "0004_alter_threadread_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thread",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="chatgroup",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="chatgroup",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="chatgroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("BAN", "Ban"),
                    ("PENDING", "Pending"),
                    ("REJECTED", "Rejected"),
                    ("DISABLED", "Disabled"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chatgroupparticipant",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="chatgroupparticipant",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="chatgroupparticipant",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("BLOCK", "Block"),
                    ("PENDING", "Pending"),
                    ("REJECTED", "Rejected"),
                    ("REMOVED", "Removed"),
                    ("DISABLED", "Disabled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="threadread",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="threadread",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="threadread",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
